spring.application.name=My Blog

# ===============================
# DATABASE CONNECTION
# ===============================

# jdbc = protocole
# postgresql/mysql = driver bdd cible
# localhost = hôte
# 5432/3306 = port
# myblog = nom de la base de données
# URL de connexion pour accéder à la base de données
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================

# ddl-auto = active ou non la generation du schema par l'application Java avec un niveau plus fin (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
# show-sql = active ou non les requetes dans les logs et la console. Generalement desactive en production pour des raisons de performance
spring.jpa.show-sql=true
# format_sql = active ou non le formatage des requetes dans les logs et la console
spring.jpa.properties.hibernate.format_sql=true
